name: Continuous Integration with Github actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2    

      # Login docker hub
      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'  

      - name: Build Eureka Naming server container image
        working-directory: ./naming-server
        run: mvn spring-boot:build-image -DskipTests

      - name: Build API Gateway Container image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests

      - name: Build Cambio Microservice Jar
        working-directory: ./cambio-service
        run: mvn clean package -DskipTests

      - name: Build Book Microservice Jar
        working-directory: ./book-service
        run: mvn clean package -DskipTests

      - name: Docker Compose Build
        working-directory: ./
        run: docker-compose build        
        
